### ISSUE TITLE
Not using Maven

### ISSUE THREAD

**Issue by fazlin26** [lotharschulz/readImageMetadata#1]
![screenshot 44](https://user-images.githubusercontent.com/44737412/49056427-a9756900-f236-11e8-85b9-d4def12a3805.png)

Hi there, I am using the usual Java class project instead of Maven. So I wonder how to use the metadata extractor library as my coding detecting errors when importing the libraries (as in the picture) even though I've been added it to my project library. Please, I really need help here, I am working on my final year project.

**Comment by lotharschulz** [comment]
I just see this now.

You can add dependencies to your java netbeans project in project->dependency as described here:  https://stackoverflow.com/a/21493665.
